name: Run Maven Tests and Push Files

on:
  push:
    branches:
      - main

jobs:
  run-tests-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        run: |
          # Nastavte potřebné oprávnění pro soubory
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven Tests
        run: mvn test

      - name: Configure Git
        run: |
          git config --local user.name "matejpaclt"
          git config --local user.email "matej.paclt@tul.cz"

      - name: Commit and Push Files
        run: |
          git add .
          git commit -m "Add test results"
          git push
